/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package whatweb;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;
import whatweb.controllers.MainKud;

import java.io.IOException;
import java.sql.SQLException;

import static javafx.application.Application.launch;

public class App extends Application {

    private Parent mainUI;

    private Stage stage;

    private MainKud mainKud;


    public void start(Stage primaryStage) throws Exception {

        stage = primaryStage;
        pantailakKargatu();

        stage.setTitle("Eurobisioa");
        stage.setScene(new Scene(mainUI,450,275));
        stage.show();
    }

    private void pantailakKargatu() throws IOException {
        FXMLLoader loaderKautotu = new FXMLLoader(getClass().getResource("/Main.fxml"));
        mainUI = (Parent) loaderKautotu.load();
        mainKud = loaderKautotu.getController();
        mainKud.setMainApp(this);
    }

    public static void main(String[] args) {
        launch(args);
    }



}
