/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package whatweb;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;
import whatweb.controllers.MainKud;
import whatweb.controllers.WWKud;

import java.io.IOException;
import java.sql.SQLException;

import static javafx.application.Application.launch;

public class App extends Application {

    private Parent mainUI;
    private Parent whatWebUI;

    private Stage stage;

    private MainKud mainKud;
    private WWKud whatWebKud;


    public void start(Stage primaryStage) throws Exception {

        stage = primaryStage;
        pantailakKargatu();

        hasieraKargatu();

    }

    private void pantailakKargatu() throws IOException {
        FXMLLoader loaderMain = new FXMLLoader(getClass().getResource("/Main.fxml"));
        mainUI = (Parent) loaderMain.load();
        mainKud = loaderMain.getController();
        mainKud.setMainApp(this);

        FXMLLoader loaderWhatWeb = new FXMLLoader(getClass().getResource("/whatweb.fxml"));
        whatWebUI = (Parent) loaderWhatWeb.load();
        whatWebKud = loaderWhatWeb.getController();
        whatWebKud.setMainApp(this);
    }

    public static void main(String[] args) {
        launch(args);
    }

    public void hasieraKargatu(){
        stage.setTitle("What Web");
        stage.setScene(new Scene(mainUI,899,732));
        stage.show();
    }


    public void whatWebErakutsi() {
        stage.setTitle("What Web");
        stage.setScene(new Scene(whatWebUI,899,732));
        stage.show();
    }
}
